sudo: required
services:
  - docker

before_install:
  - docker build -t kaustav1808/simpleweb -f dockerfile.dev .

script:
  - docker run -e CI=true kaustav1808/simpleweb npm run test -- --coverage  

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-simpleweb"
  environment: "dockersimpleweb-env"
  bucket_name: "elasticbeanstalk-ap-south-1-037966023887"
  bucket_path: "docker-simpleweb"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

    